---
description: When the quickaction /ship is executed
internal_events: true
action: i_quickactions_ship
identifiers:
- project
- namespace
- user
product_group: code_review
product_categories:
- code_review_workflow
milestone: '18.6'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78998
tiers:
- free
- premium
- ultimate
