name: user_mapping_direct_reassignment
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/521450
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/209033
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/575652
milestone: '18.6'
group: group::import
type: beta
default_enabled: false
